public class tryCatchProblem {
    public static void main(String[] args) {
        try {
            int arr[] = { 1, 2, 3, 4 };

            System.out.println(arr[3847564]);
        } catch (Exception e) {
            System.out.println("some thing went wrong");
        }
    }
}
